# Example override for Odoo 18 stack - mount addons on the host
# On server: copy to /root/libya/dev-18/docker-compose.override.yml
# so that ./addons is used as extra addons path.

version: '3.6'
services:
  odoo18:
    volumes:
      - ./addons:/mnt/extra-addons
    command: --addons-path=/mnt/extra-addons
